config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ideas
  resources :users
  get 'tags/:tag', to: 'ideas#index', as: :tag
  root "ideas#index"
end

app/models/idea.rb
class Idea < ActiveRecord::Base

	has_many :requirements
	has_many :qualifications
	belongs_to :user

	acts_as_taggable
	acts_as_taggable_on :category

	
	accepts_nested_attributes_for :requirements, reject_if: proc { |attributes| attributes['name'].blank? },
		allow_destroy: true
	accepts_nested_attributes_for :qualifications, reject_if: proc { |attributes| attributes['add'].blank? },
		allow_destroy: true
	

	has_attached_file :image, styles: { :medium => "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	validates :description, presence: true, length: { maximum: 80 }
	validates :title, :image, presence: true
end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
  belongs_to :idea
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  belongs_to :idea
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ideas

  acts_as_taggable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name,:tag_list, :email, :password, :current_password, :is_female, :birthday,:commitment,:user_description, :website) }
        end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
	before_action :find_idea, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@idea = Idea.all.order("created_at DESC")

		if params[:tag].present? 
      @idea = Idea.tagged_with(params[:tag])
    else
      @idea = Idea.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
      respond_to do |format|
	      format.html  #index.html.erb
	      format.json { render json: @ideas }
      end 
    end  
	end

	
	def show
	end

	def new
		@idea = current_user.ideas.build
	end


	def create
		@idea = current_user.ideas.build(idea_params)
		if @idea.save
			redirect_to @idea, notice: "Succesfully created new idea"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @idea.update(idea_params)
		redirect_to @idea
		else
		render 'edit'
		end
	end

	def destroy
		@idea.destroy
		redirect_to root_path, notice: "Succesfully deleted idea"
	end

	
	private

	def idea_params
		params.require(:idea).permit(:title, :description, :image, :tag_list, requirements_attributes: [:id, :name, :_destroy], qualifications_attributes: [:id, :add, :_destroy])
	end

	def find_idea
		@idea = Idea.find(params[:id])		
	end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  def show
    @user = User.find(params[:id])


		if params[:tag].present? 
	    @user = User.tagged_with(params[:tag])
	  end  



    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<%= simple_form_for @idea, html: { multipart: true } do |f| %>
  <% if @idea.errors.any? %>
    <div id="errors">
      <p>
        <%= @idea.errors.count %>
        Prevented this idea from saving
      </p>
      <ul>
        <% @idea.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="panel-body">
  <%= f.input :title, input_html: { class: 'form-control' } %>
  <%= f.input :description, input_html: { class: 'form-control' } %>
  <p>mini description - ("airbnb for parking" etc) max 80 chars</p>
  



    <% @idea.tag_types.each do |tag| %>
  <div class="form-group">
    <strong><%= f.label tag.to_s.titleize %></strong><br />
    <% tag_sym = "#{tag.to_s.singularize}_list".to_sym %>
    <% tag_list = "#{tag.to_s.singularize}_list" %>
    <%= f.text_field tag_sym, value: @idea.send(tag_list).to_s, :placeholder => "Comma-separated list of #{tag.to_s}", class: 'form-control' %>
  </div>
  <% end %>

  <%= f.input :image, input_html: { class: 'form-control' } %>
  <div class="row">
    <div class="col-md-6">
      <h3>Requirements</h3>
      <div id="requirements">
        <%= f.simple_fields_for :requirements do |requirement| %>
          <%= render 'requirement_fields', f: requirement %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'Add Requirement', f, :requirements, class: "btn btn-default add-button" %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <h3>Qualifications</h3>
    <div id="qualifications">
      <%= f.simple_fields_for :qualifications do |qualification| %>
        <%= render 'qualification_fields', f: qualification %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'Add Qualification', f, :qualifications, class: "btn btn-default add-button" %>
      </div>
    </div>
  </div>
</div>
<%= f.button :submit, class: "btn btn-primary" %>

<% end %>

app/views/ideas/_qualification_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :add, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove", f, class: "btn btn-default form-button" %>
  </div>
</div>

app/views/ideas/_requirement_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/ideas/edit.html.erb
<h1>Edit idea</h1>
<%= render 'form' %>

app/views/ideas/index.html.erb
<% @idea.each_slice(3) do |ideas| %>
  <div class="row">
    <% ideas.each do |idea| %>
      <div class="col-md-4">
        <div class="idea">
          <div class="image_wrapper">
            <%= link_to idea do %>
              <%= image_tag idea.image.url(:medium) %>
            <% end %>
          </div>
          <h2>
            <%= link_to idea.title, idea %>
          </h2>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>
<%= render 'form' %>
<br/>
<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/ideas/show.html.erb
<div class="main_content">
  <div class="row" id="recipe_top">
    <div class="col-md-4">
      <%= image_tag @idea.image.url(:medium), class: "idea_image" %>
    </div>
    <div class="col-md-8">
      <div id="idea_info">
        <div class="container">
          <h1>
            <%= @idea.title %>
          </h1>
          <p class="description">
            <%= @idea.description %>
          </p>
          <p>
            Submitted by
            <%= @idea.user.email %>
          </p>
          <p>More ideas with this technology:</p>
          <% @idea.tags.any? %>
            <% @idea.tags.each do |tag| %>
            <span class="label label-teal">
              <%= link_to tag.name, tag_path(tag.name) %>
            </span>  
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

  <div class="row">
    <div class="col-md-6">
      <div id="requirements">
        <h2>Requirements</h2>
        <ul>
          <% @idea.requirements.each do |requirement| %>
            <li>
              <%= requirement.name %>
              <%= link_to "Apply for this", @idea, class: "btn btn-primary" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div id="qualifications">
      <h2>Qualifications</h2>
      <ul>
        <% @idea.qualifications.each do |qualification| %>
          <li>
            <%= qualification.add %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
      <% if user_signed_in? %>

        <%= link_to "Edit", edit_idea_path, class: "btn btn-default" %>
        <%= link_to "Delete", idea_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Idea App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "Idea Box", root_path %>
      </div>
    </div>
  </nav>
  <% if user_signed_in? %>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to "New Idea", new_idea_path %>
      </li>
      <li>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </li>
      <li>
        <%= link_to 'Edit Profile',edit_user_registration_path %>
      </li>
      <li>
        <%= link_to 'My Profile',user_path(current_user.id) %>
      </li>

    </ul>
  <% else %>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to "Sign Up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Sign In", new_user_session_path %>
      </li>
    </ul>
  <% end %>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert" %>
    <% end %>
  </div>
  <%= yield %>
</body>
</html>

app/views/users/index.html.erb
    <% @users.each do |user| %>
      <div class="col-md-4">
        <div class="user">
          <h2>
            <%= link_to user.name, user %>
          </h2>
        </div>
      </div>
    <% end %>


app/views/users/show.html.erb
<div class="main_content">
  <div class="row" id="recipe_top">
    <div class="col-md-8">
      
        <div class="container">
          <h1>
            <%= @user.name %> 
          </h1>
            <h3>Commitment:</h3>
            	<%= @user.commitment %>

            <h3>Website:</h3>
              <%=link_to @user.website, "http://#{@user.website}"%>

            <h3>Birthday:</h3>
            	<%= @user.birthday %>
            <h3>Short Bio:</h3>
            	<%= @user.user_description %>

						<h3>All users:</h3>
            	<%= link_to "Show ",users_path %>

            <h3>My Skills:</h3>
              <% @user.tags.any? %>
                <% @user.tags.each do |tag| %>
                <span class="label label-teal">
                  <%= link_to tag.name, tag_path(tag.name) %>  
                </span>
          <% end %>

          	
        </div>
    </div>
  </div>
</div>

    <div class="row">
    <div class="col-md-12">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
    </div>
  </div>
</div>